REBOL [
	title: "Simple launcher"
	file: %simple-launcher.r
	author: "Marco Antoniazzi"
	email: [luce80 AT libero DOT it]
	date: 22-05-2011
	version: 0.2.0
	comment: {GUI automatically generated by VID_build. Author: Marco Antoniazzi}
	Purpose: "A simple gui to launch a REBOL script."
	Category: [util view]
	library: [
		level: 'beginner
		platform: 'all
		type: 'tool
		domain: [gui vid files]
		tested-under: [View 2.7.8.3.1]
		support: none
		license: 'BSD
		see-also: none
	]
]
		
load_file: func [/local file-name] [
	until [
		file-name: request-file/title/keep/only/filter "Load a Rebol script" "Load" "*.r"
		if none? file-name [return ""]
		exists? file-name
	]
	file-name
]

view/title center-face layout [
	do [sp: 4x4] origin sp space sp
	Across
	filename: field 300
	btn "..." #"^o" [set-face filename load_file]
	btn "Run" green #"^M" [if all [%"" <> file: to-file trim get-face filename  exists? file] [attempt [launch file]]]
] "Launcher"