; THIS FILE WAS GENERATED BY make-filters.r
; DO NOT EDIT BY HAND!
level-beginner
["" [idx-match 'beginner library/level]]
level-intermediate
["" [idx-match 'intermediate library/level]]
level-advanced
["" [idx-match 'advanced library/level]]
platform-all
["" [idx-match 'all library/platform]]
platform-windows
["" [idx-match 'windows library/platform]]
platform-win
["" [idx-match 'win library/platform]]
platform-linux
["" [idx-match 'linux library/platform]]
platform-mac
["" [idx-match 'mac library/platform]]
platform-unix
["" [idx-match 'unix library/platform]]
platform-*nix
["" [idx-match '*nix library/platform]]
platform-solaris
["" [idx-match 'solaris library/platform]]
platform-amiga
["" [idx-match 'amiga library/platform]]
platform-be
["" [idx-match 'be library/platform]]
platform-plugin
["" [idx-match 'plugin library/platform]]
type-Demo
["" [idx-match 'Demo library/type]]
type-Tool
["" [idx-match 'Tool library/type]]
type-Game
["" [idx-match 'Game library/type]]
type-Package
["" [idx-match 'Package library/type]]
type-Fun
["" [idx-match 'Fun library/type]]
type-Rebcode
["" [idx-match 'Rebcode library/type]]
type-Reference
["" [idx-match 'Reference library/type]]
type-How-to
["" [idx-match 'How-to library/type]]
type-FAQ
["" [idx-match 'FAQ library/type]]
type-Article
["" [idx-match 'Article library/type]]
type-Tutorial
["" [idx-match 'Tutorial library/type]]
type-Idiom
["" [idx-match 'Idiom library/type]]
type-one-liner
["" [idx-match 'one-liner library/type]]
type-function
["" [idx-match 'function library/type]]
type-module
["" [idx-match 'module library/type]]
type-protocol
["" [idx-match 'protocol library/type]]
type-dialect
["" [idx-match 'dialect library/type]]
domain-math
["" [idx-match 'math library/domain]]
domain-financial
["" [idx-match 'financial library/domain]]
domain-scientific
["" [idx-match 'scientific library/domain]]
domain-UI
["" [idx-match 'UI library/domain]]
domain-user-interface
["" [idx-match 'user-interface library/domain]]
domain-GUI
["" [idx-match 'GUI library/domain]]
domain-VID
["" [idx-match 'VID library/domain]]
domain-graphics
["" [idx-match 'graphics library/domain]]
domain-sound
["" [idx-match 'sound library/domain]]
domain-animation
["" [idx-match 'animation library/domain]]
domain-web
["" [idx-match 'web library/domain]]
domain-http
["" [idx-match 'http library/domain]]
domain-ftp
["" [idx-match 'ftp library/domain]]
domain-cgi
["" [idx-match 'cgi library/domain]]
domain-tcp
["" [idx-match 'tcp library/domain]]
domain-email
["" [idx-match 'email library/domain]]
domain-ldc
["" [idx-match 'ldc library/domain]]
domain-ssl
["" [idx-match 'ssl library/domain]]
domain-other-net
["" [idx-match 'other-net library/domain]]
domain-protocol
["" [idx-match 'protocol library/domain]]
domain-scheme
["" [idx-match 'scheme library/domain]]
domain-extension
["" [idx-match 'extension library/domain]]
domain-testing
["" [idx-match 'testing library/domain]]
domain-security
["" [idx-match 'security library/domain]]
domain-DB
["" [idx-match 'DB library/domain]]
domain-database
["" [idx-match 'database library/domain]]
domain-odbc
["" [idx-match 'odbc library/domain]]
domain-mysql
["" [idx-match 'mysql library/domain]]
domain-sql
["" [idx-match 'sql library/domain]]
domain-files
["" [idx-match 'files library/domain]]
domain-file-handling
["" [idx-match 'file-handling library/domain]]
domain-text
["" [idx-match 'text library/domain]]
domain-text-processing
["" [idx-match 'text-processing library/domain]]
domain-markup
["" [idx-match 'markup library/domain]]
domain-html
["" [idx-match 'html library/domain]]
domain-xml
["" [idx-match 'xml library/domain]]
domain-parse
["" [idx-match 'parse library/domain]]
domain-dialects
["" [idx-match 'dialects library/domain]]
domain-printing
["" [idx-match 'printing library/domain]]
domain-AI
["" [idx-match 'AI library/domain]]
domain-visualization
["" [idx-match 'visualization library/domain]]
domain-encryption
["" [idx-match 'encryption library/domain]]
domain-compression
["" [idx-match 'compression library/domain]]
domain-x-file
["" [idx-match 'x-file library/domain]]
domain-win-api
["" [idx-match 'win-api library/domain]]
domain-external-library
["" [idx-match 'external-library library/domain]]
domain-shell
["" [idx-match 'shell library/domain]]
domain-patch
["" [idx-match 'patch library/domain]]
domain-sdk
["" [idx-match 'sdk library/domain]]
domain-debug
["" [idx-match 'debug library/domain]]
domain-game
["" [idx-match 'game library/domain]]
domain-dead
["" [idx-match 'dead library/domain]]
domain-broken
["" [idx-match 'broken library/domain]]
license-bsd
["" [idx-match 'bsd library/license]]
license-cc-by
["" [idx-match 'cc-by library/license]]
license-cc-by-sa
["" [idx-match 'cc-by-sa library/license]]
license-gpl
["" [idx-match 'gpl library/license]]
license-lgpl
["" [idx-match 'lgpl library/license]]
license-mit
["" [idx-match 'mit library/license]]
license-public-domain
["" [idx-match 'public-domain library/license]]
license-pd
["" [idx-match 'pd library/license]]
license-rvd
["" [idx-match 'rvd library/license]]
